version: 0.2

phases:
  install:
    commands:
      - echo Installing Composer...
      - curl -sS https://getcomposer.org/installer | php
      - php composer.phar install

  build:
    commands:
      - echo Build started...
      - cp .env.example .env
      - php artisan key:generate
      - mkdir -p storage/framework/views
      - mkdir -p storage/framework/cache
      - mkdir -p storage/logs
      - mkdir -p bootstrap/cache
      - chmod -R 777 storage
      - chmod -R 777 bootstrap/cache
      - php artisan config:clear
      - php artisan config:cache

artifacts:
  files:
    - '**/*'
